name: Bash CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  check-bash:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Install shell check
        run: sudo apt-get install -y shellcheck
      - name: linting
        run: shellcheck analyse.sh
      - name: make executable
        run: chmod +x analyse.sh
      - name: run the scrpit
        run: ./analyse.sh
